In [35]:
import pandas as pd

Import raw file to clean

In [36]:
df = pd.read_csv("LiveLongerData.csv")
df.head()

,Factor,Years gained / lost,strength of science?,strength of science as a number,sexes affected,effect,Comment,Note,ID,Sources,Links
0,Smoking,-10.0,strong,3,Both,negative,10 years gained (against those who continue to...,14 if combined with exercise and eating health...,1,"Khaw KT, et al. (2008). Combined impact of hea...",http://www.washingtonpost.com/wp-dyn/articles/...
1,Sitting Down,-3.0,suggestive,1,Both,negative,for 8-11 hours sitting a day,"No matter how much you exercise, sitting too m...",2,Sydney School of Public Health research paper ...,http://www.ncbi.nlm.nih.gov/pubmed/22450936
2,Too much sleeping,-1.5,suggestive,1,Both,negative,"7 hours ideal, no more than 8 hrs a night",Averaging more than 8 hours sleep a night will...,3,New Scientist,http://www.newscientist.com/article/dn1928-sev...
3,More Optimism,2.0,suggestive,1,Female,positive,& faith in fellow humans. calc takes average %...,Women within the highest 25% of optimism score...,4,"Source: Hilary A. Tindle, M.D., assistant prof...",www.nlm.nih.gov/medlineplus/news/fullstory_879...
4,More Pets,3.0,good,2,Both,positive,particularly for elderly. calc assumes that he...,(1) Cats - According to a study by the Minneso...,5,Medical News Today; National Center for Biotec...,http://www.medicalnewstoday.com/articles/98432...

Check what columns are there

In [37]:
df.columns

Index(['Factor', 'Years gained / lost', 'strength of science?',
       'strength of science as a number', 'sexes affected', 'effect',
       'Comment', 'Note', 'ID', 'Sources', 'Links'],
      dtype='object')

Only keep data with good or strong scientific evidence

In [38]:
df = df[df["strength of science?"].isin(["strong", "good"])]

In [39]:
df.head()

,Factor,Years gained / lost,strength of science?,strength of science as a number,sexes affected,effect,Comment,Note,ID,Sources,Links
0,Smoking,-10.0,strong,3,Both,negative,10 years gained (against those who continue to...,14 if combined with exercise and eating health...,1,"Khaw KT, et al. (2008). Combined impact of hea...",http://www.washingtonpost.com/wp-dyn/articles/...
4,More Pets,3.0,good,2,Both,positive,particularly for elderly. calc assumes that he...,(1) Cats - According to a study by the Minneso...,5,Medical News Today; National Center for Biotec...,http://www.medicalnewstoday.com/articles/98432...
6,Healthy Eating,7.0,strong,3,Both,positive,Japanese / Mediterannean diet will lengthen li...,Figure given for Mediterannean diet. JAPANESE:...,7,Amazon (book) The Okinawa Program : How the Wo...,http://www.amazon.com/Okinawa-Program-Longest-...
7,Red Meat,-1.0,good,2,Both,positive,NaN,risk of dying in a given year increases by 13%...,8,BBC News,http://www.bbc.co.uk/news/magazine-17389938
8,Alcohol (heavy abuse),-11.0,good,2,Both,positive,a lot is bad,Alcoholism reduces life expectancy by about 10...,9,New York Times,http://health.nytimes.com/health/guides/diseas...

Drop unnecessary columns

In [40]:
df = df.drop(['strength of science?',
       'strength of science as a number', 'sexes affected', 'effect',
       'Comment', 'Note', 'ID', 'Sources', 'Links'], axis=1)
df

                                               Factor  Years gained / lost
0                                             Smoking               -10.00
4                                           More Pets                 3.00
6                                      Healthy Eating                 7.00
7                                            Red Meat                -1.00
8                               Alcohol (heavy abuse)               -11.00
10                                     Mental Illness               -25.00
11                                            Obesity                -8.50
12                              More Health Checks #2                 0.14
13                            Living at high altitude                 2.00
14                                      Good marriage                10.00
18  a lifestyle of non-smoking, exercising, and he...                14.00
21                                      More Exercise                 2.00
26                                         More Money                 7.50
27                                      being a woman                 5.10
32                                      Good genetics                 5.00
33                                  A little exercise                 2.00
34                                        Pets - dogs                 3.00

Drop unnecessary rows

In [41]:
rows_to_drop = df[df["Factor"].isin(["Pets - dogs", "Good genetics", "being a woman", "Living at high altitude", "More Health Checks #2"])].index

df = df.drop(rows_to_drop)

In [42]:
df

                                               Factor  Years gained / lost
0                                             Smoking                -10.0
4                                           More Pets                  3.0
6                                      Healthy Eating                  7.0
7                                            Red Meat                 -1.0
8                               Alcohol (heavy abuse)                -11.0
10                                     Mental Illness                -25.0
11                                            Obesity                 -8.5
14                                      Good marriage                 10.0
18  a lifestyle of non-smoking, exercising, and he...                 14.0
21                                      More Exercise                  2.0
26                                         More Money                  7.5
33                                  A little exercise                  2.0

Change name of the Factors

In [43]:
df.loc[4, "Factor"] = "Pets"
df.loc[8, "Factor"] = "Heavy alcohol consumption"
df.loc[18, "Factor"] = "Non-smoking, exercising and healthy diet"
df.loc[21, "Factor"] = "Moderate exercise"
df

                                      Factor  Years gained / lost
0                                    Smoking                -10.0
4                                       Pets                  3.0
6                             Healthy Eating                  7.0
7                                   Red Meat                 -1.0
8                  Heavy alcohol consumption                -11.0
10                            Mental Illness                -25.0
11                                   Obesity                 -8.5
14                             Good marriage                 10.0
18  Non-smoking, exercising and healthy diet                 14.0
21                         Moderate exercise                  2.0
26                                More Money                  7.5
33                         A little exercise                  2.0

In [44]:
df.to_csv("longevity_factor_cleaned.csv", index=False)